export const COMPANY_LIST_REQUEST = 'COMPANY_LIST_REQUEST';
export const COMPANY_LIST_SUCCESS = 'COMPANY_LIST_SUCCESS';
export const COMPANY_LIST_FAIL = 'COMPANY_LIST_FAIL';

export const COMPANY_DETAILS_REQUEST = 'COMPANY_DETAILS_REQUEST';
export const COMPANY_DETAILS_SUCCESS = 'COMPANY_DETAILS_SUCCESS';
export const COMPANY_DETAILS_FAIL = 'COMPANY_DETAILS_FAIL';

export const COMPANY_NAME_CREATE_REQUEST = 'COMPANY_NAME_CREATE_REQUEST';
export const COMPANY_NAME_CREATE_SUCCESS = 'COMPANY_NAME_CREATE_SUCCESS';
export const COMPANY_NAME_CREATE_FAIL = 'COMPANY_NAME_CREATE_FAIL';
export const COMPANY_NAME_CREATE_RESET = 'COMPANY_NAME_CREATE_RESET';

export const COMPANY_NAME_UPDATE_REQUEST = 'COMPANY_NAME_UPDATE_REQUEST';
export const COMPANY_NAME_UPDATE_SUCCESS = 'COMPANY_NAME_UPDATE_SUCCESS';
export const COMPANY_NAME_UPDATE_FAIL = 'COMPANY_NAME_UPDATE_FAIL';
export const COMPANY_NAME_UPDATE_RESET = 'COMPANY_NAME_UPDATE_RESET';
