export const COMPENSATIONS_LIST_REQUEST = 'COMPENSATIONS_LIST_REQUEST';
export const COMPENSATIONS_LIST_SUCCESS = 'COMPENSATIONS_LIST_SUCCESS';
export const COMPENSATIONS_LIST_FAIL = 'COMPENSATIONS_LIST_FAIL';

export const COMPENSATIONS_CREATE_REQUEST = 'COMPENSATIONS_CREATE_REQUEST';
export const COMPENSATIONS_CREATE_SUCCESS = 'COMPENSATIONS_CREATE_SUCCESS';
export const COMPENSATIONS_CREATE_FAIL = 'COMPENSATIONS_CREATE_FAIL';
export const COMPENSATIONS_CREATE_RESET = 'COMPENSATIONS_CREATE_RESET';

export const COMPENSATIONS_DELETE_REQUEST = 'COMPENSATIONS_DELETE_REQUEST';
export const COMPENSATIONS_DELETE_SUCCESS = 'COMPENSATIONS_DELETE_SUCCESS';
export const COMPENSATIONS_DELETE_FAIL = 'COMPENSATIONS_DELETE_FAIL';
