export const DEPARTMENT_CREATE_REQUEST = 'DEPARTMENT_CREATE_REQUEST';
export const DEPARTMENT_CREATE_SUCCESS = 'DEPARTMENT_CREATE_SUCCESS';
export const DEPARTMENT_CREATE_FAIL = 'DEPARTMENT_CREATE_FAIL';
