export const NON_TAXABLE_PAYS_LIST_REQUEST = 'NON_TAXABLE_PAYS_LIST_REQUEST';
export const NON_TAXABLE_PAYS_LIST_SUCCESS = 'NON_TAXABLE_PAYS_LIST_SUCCESS';
export const NON_TAXABLE_PAYS_LIST_FAIL = 'NON_TAXABLE_PAYS_LIST_FAIL';

export const NON_TAXABLE_PAYS_CREATE_REQUEST = 'NON_TAXABLE_PAYS_CREATE_REQUEST';
export const NON_TAXABLE_PAYS_CREATE_SUCCESS = 'NON_TAXABLE_PAYS_CREATE_SUCCESS';
export const NON_TAXABLE_PAYS_CREATE_FAIL = 'NON_TAXABLE_PAYS_CREATE_FAIL';

export const NON_TAXABLE_PAYS_DELETE_REQUEST = 'NON_TAXABLE_PAYS_DELETE_REQUEST';
export const NON_TAXABLE_PAYS_DELETE_SUCCESS = 'NON_TAXABLE_PAYS_DELETE_SUCCESS';
export const NON_TAXABLE_PAYS_DELETE_FAIL = 'NON_TAXABLE_PAYS_DELETE_FAIL';
export const NON_TAXABLE_PAYS_DELETE_RESET = 'NON_TAXABLE_PAYS_DELETE_RESET';

export const NON_TAXABLE_PAYS_UPDATE_REQUEST = 'NON_TAXABLE_PAYS_UPDATE_REQUEST';
export const NON_TAXABLE_PAYS_UPDATE_SUCCESS = 'NON_TAXABLE_PAYS_UPDATE_SUCCESS';
export const NON_TAXABLE_PAYS_UPDATE_FAIL = 'NON_TAXABLE_PAYS_UPDATE_FAIL';
export const NON_TAXABLE_PAYS_UPDATE_RESET = 'NON_TAXABLE_PAYS_UPDATE_RESET';
