export const TAXABLE_PAYS_LIST_REQUEST = 'TAXABLE_PAYS_LIST_REQUEST';
export const TAXABLE_PAYS_LIST_SUCCESS = 'TAXABLE_PAYS_LIST_SUCCESS';
export const TAXABLE_PAYS_LIST_FAIL = 'TAXABLE_PAYS_LIST_FAIL';

export const TAXABLE_PAYS_CREATE_REQUEST = 'TAXABLE_PAYS_CREATE_REQUEST';
export const TAXABLE_PAYS_CREATE_SUCCESS = 'TAXABLE_PAYS_CREATE_SUCCESS';
export const TAXABLE_PAYS_CREATE_FAIL = 'TAXABLE_PAYS_CREATE_FAIL';
