# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Api Dependencies
      run: npm install
    - name: Install Client Dependencies
      run: yarn install --prefix client

    - name: Build
      run: npm build

    - name: Test API
      run: npm run test:api
    - name: Test Client
      run: npm run test:client
